/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useEffect, useState, useCallback} from 'react';
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableNativeFeedback,
} from 'react-native';
import {getBadgeCount, setBadgeCount} from 'react-native-notification-badge';

export default function App() {
  const [badgeCount, _setBadgeCount] = useState(undefined);
  const [text, setText] = useState('');

  const loadBadgeCount = useCallback(async () => {
    const _badgeCount = await getBadgeCount();
    _setBadgeCount(_badgeCount);
  }, []);
  const updateBadgeCount = useCallback(async () => {
    const number = parseInt(text, 10);
    if (typeof number === 'number' && !isNaN(number)) {
      setBadgeCount(number);
      setText('');
    }
    await loadBadgeCount();
  }, [text, loadBadgeCount]);

  useEffect(() => {
    loadBadgeCount();
  }, [loadBadgeCount]);

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>NotificationBadge</Text>
      <Text>Current Badge Count: {badgeCount}</Text>
      <View style={styles.row}>
        <TextInput
          style={styles.textInput}
          onChangeText={setText}
          value={text}
          placeholder={'Badge Count'}
        />
        <TouchableNativeFeedback
          style={styles.button}
          onPress={updateBadgeCount}>
          <Text>Set</Text>
        </TouchableNativeFeedback>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  row: {
    marginTop: 20,
    flexDirection: 'row',
    width: '50%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  textInput: {
    fontSize: 16,
  },
  button: {
    fontSize: 16,
  },
});
